/**
 * ImplementationPlan generator + validator — T-M4-004,
 * spec §12.5.
 *
 * The plan is what cgao executes against. It is:
 *
 *   - GENERATED by an LLM (driven by PlanPromptTemplate), then VALIDATED
 *     deterministically.
 *   - BOUND to a RequirementSpec (by spec.issueSnapshotSha + plan's
 *     requirementSpecDigest).
 *   - IMMUTABLE once persisted: plan_id and plan_sha together lock it.
 *
 * Contracts (spec §12.5):
 *
 *   - Every acceptanceCriterion on the spec maps to ≥1 task in the plan.
 *   - Each task has allowed_paths, forbidden_paths, depends_on, agent,
 *     model_tier.
 *   - forbidden_paths MUST include any protected path not explicitly
 *     allow-listed by the deterministic risk classifier's matches.
 *   - plan_sha = sha256(canonical JSON of the plan body).
 */

import { createHash } from 'node:crypto';
import { z } from 'zod';
import type { RequirementSpec } from './requirement-spec.js';
import { type PathMatch, type RuleEvaluationResult, severityRank } from './risk-classifier.js';

export const modelTierSchema = z.enum(['low', 'standard', 'high', 'frontier']);
export type ModelTier = z.infer<typeof modelTierSchema>;

export const agentKindSchema = z.enum([
  'explorer',
  'implementer',
  'tester',
  'reviewer',
  'committer',
]);
export type AgentKind = z.infer<typeof agentKindSchema>;

export const implementationTaskSchema = z.object({
  /** Stable task id (e.g. 't1', 't2'). Unique within the plan. */
  id: z.string().min(1),
  /** Acceptance-criterion ids this task satisfies (≥1). */
  satisfies: z.array(z.string().min(1)).min(1),
  /** Human-readable description. */
  description: z.string().min(1),
  /** Paths this task is allowed to read/write. */
  allowedPaths: z.array(z.string().min(1)).min(1),
  /** Paths this task must NOT touch — enforced by FS sandbox. */
  forbiddenPaths: z.array(z.string().min(1)).default([]),
  /** Task ids that must complete before this one can start. */
  dependsOn: z.array(z.string().min(1)).default([]),
  /** Agent that should run this task. */
  agent: agentKindSchema,
  /** Model tier the runner should pick for this task. */
  modelTier: modelTierSchema,
});
export type ImplementationTask = z.infer<typeof implementationTaskSchema>;

export const implementationPlanSchema = z.object({
  /** Repo full name. */
  repo: z.string(),
  /** Issue number. */
  issueNumber: z.number().int().positive(),
  /** SHA-256 of the RequirementSpec the plan was generated from. */
  requirementSpecDigest: z.string().length(64),
  /** sha256(canonical JSON of the plan body, excluding planSha itself). */
  planSha: z.string().length(64),
  /** Short slug-style id (e.g. 'plan-0001'). */
  planId: z.string().min(1),
  /** Tasks — must cover every acceptance criterion. */
  tasks: z.array(implementationTaskSchema).min(1),
  /** Generation counter (matches the spec's generation). */
  generation: z.number().int().nonnegative(),
  /** ISO-8601 created_at. */
  createdAt: z.string(),
});
export type ImplementationPlan = z.infer<typeof implementationPlanSchema>;

/**
 * Map an acceptance criterion to a stable id (used to verify every
 * criterion is covered by ≥1 task).
 */
export function acceptanceCriterionId(_spec: RequirementSpec, index: number): string {
  return `ac-${index + 1}`;
}

/**
 * Compute the plan body digest. The digest is taken over the CANONICAL
 * JSON (sorted keys, no whitespace) of the plan body, EXCLUDING the
 * plan_sha field itself (which is the digest).
 */
export function computePlanDigest(args: {
  repo: string;
  issueNumber: number;
  requirementSpecDigest: string;
  planId: string;
  tasks: readonly ImplementationTask[];
  generation: number;
  createdAt: string;
}): string {
  const body = {
    createdAt: args.createdAt,
    generation: args.generation,
    issueNumber: args.issueNumber,
    planId: args.planId,
    repo: args.repo,
    requirementSpecDigest: args.requirementSpecDigest,
    tasks: args.tasks.map(canonicalTask),
  };
  return sha256Canonical(body);
}

function canonicalTask(t: ImplementationTask): Record<string, unknown> {
  return {
    agent: t.agent,
    allowedPaths: [...t.allowedPaths].sort(),
    dependsOn: [...t.dependsOn].sort(),
    description: t.description,
    forbiddenPaths: [...t.forbiddenPaths].sort(),
    id: t.id,
    modelTier: t.modelTier,
    satisfies: [...t.satisfies].sort(),
  };
}

function sha256Canonical(value: unknown): string {
  const json = stableJsonStringify(value);
  return createHash('sha256').update(json).digest('hex');
}

/**
 * Deterministic JSON.stringify — object keys sorted ascending at every
 * level, arrays preserved in source order, UTF-8 clean. Avoids
 * locale-dependent ordering of Array.prototype.sort.
 */
function stableJsonStringify(value: unknown): string {
  if (value === null || typeof value !== 'object') {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    const items = value.map(stableJsonStringify);
    return `[${items.join(',')}]`;
  }
  const keys = Object.keys(value as Record<string, unknown>).sort();
  const pairs = keys.map((k) => {
    const v = (value as Record<string, unknown>)[k];
    return `${JSON.stringify(k)}:${stableJsonStringify(v)}`;
  });
  return `{${pairs.join(',')}}`;
}

/**
 * Build a plan from raw task input. Stamps planSha + planId. Pure.
 */
export function buildImplementationPlan(args: {
  spec: RequirementSpec;
  requirementSpecDigest: string;
  tasks: readonly ImplementationTask[];
  planId: string;
  generation?: number;
  now?: Date;
}): ImplementationPlan {
  const now = (args.now ?? new Date()).toISOString();
  const body = {
    repo: args.spec.repo,
    issueNumber: args.spec.issueNumber,
    requirementSpecDigest: args.requirementSpecDigest,
    planId: args.planId,
    tasks: args.tasks,
    generation: args.generation ?? args.spec.generation,
    createdAt: now,
  };
  const planSha = computePlanDigest(body);
  return implementationPlanSchema.parse({ ...body, planSha });
}

export interface PlanValidationFinding {
  /** 'error' rejects the plan; 'warning' surfaces to the user. */
  level: 'error' | 'warning';
  /** Code for tests + UI (e.g. 'unmapped_criterion'). */
  code: string;
  /** Human-readable message. */
  message: string;
  /** Path/field that triggered the finding (for UI highlighting). */
  field?: string;
}

export interface PlanValidatorOptions {
  /**
   * When the deterministic classifier returns matches, every task must
   * explicitly list each protected pattern in forbiddenPaths (or the
   * plan must justify allowing it). Default: true.
   */
  readonly enforceForbiddenProtectedPaths?: boolean;
}

export class PlanValidator {
  constructor(private readonly options: PlanValidatorOptions = {}) {}

  validate(args: {
    spec: RequirementSpec;
    plan: ImplementationPlan;
    deterministicRisk: RuleEvaluationResult;
  }): PlanValidationFinding[] {
    const findings: PlanValidationFinding[] = [];
    const { spec, plan, deterministicRisk } = args;

    // 1. Every acceptance criterion maps to ≥1 task.
    const criterionIds = spec.acceptanceCriteria.map((_, i) => acceptanceCriterionId(spec, i));
    const satisfied = new Set<string>();
    for (const task of plan.tasks) {
      for (const id of task.satisfies) satisfied.add(id);
    }
    for (const cid of criterionIds) {
      if (!satisfied.has(cid)) {
        findings.push({
          level: 'error',
          code: 'unmapped_criterion',
          message: `acceptance criterion ${cid} is not satisfied by any task`,
          field: 'tasks.satisfies',
        });
      }
    }

    // 2. depends_on must reference real task ids, no cycles.
    const taskIds = new Set(plan.tasks.map((t) => t.id));
    const seenAlias = new Set<string>();
    for (const t of plan.tasks) {
      if (seenAlias.has(t.id)) {
        findings.push({
          level: 'error',
          code: 'duplicate_task_id',
          message: `duplicate task id ${t.id}`,
          field: 'tasks.id',
        });
      }
      seenAlias.add(t.id);
      for (const dep of t.dependsOn) {
        if (!taskIds.has(dep)) {
          findings.push({
            level: 'error',
            code: 'unknown_dependency',
            message: `task ${t.id} depends on unknown task ${dep}`,
            field: 'tasks.dependsOn',
          });
        }
      }
    }
    if (findsCycle(plan.tasks)) {
      findings.push({
        level: 'error',
        code: 'dependency_cycle',
        message: 'task dependency graph contains a cycle',
        field: 'tasks.dependsOn',
      });
    }

    // 3. allowed_paths ∩ forbidden_paths must be empty.
    for (const t of plan.tasks) {
      const allow = new Set(t.allowedPaths);
      for (const f of t.forbiddenPaths) {
        if (allow.has(f)) {
          findings.push({
            level: 'error',
            code: 'path_in_both_lists',
            message: `task ${t.id} lists ${f} in both allowedPaths and forbiddenPaths`,
            field: 'tasks.allowedPaths',
          });
        }
      }
    }

    // 4. Plan digest must match (deterministic check).
    const recomputed = computePlanDigest({
      createdAt: plan.createdAt,
      generation: plan.generation,
      issueNumber: plan.issueNumber,
      planId: plan.planId,
      repo: plan.repo,
      requirementSpecDigest: plan.requirementSpecDigest,
      tasks: plan.tasks,
    });
    if (recomputed !== plan.planSha) {
      findings.push({
        level: 'error',
        code: 'plan_sha_mismatch',
        message: 'plan_sha does not match canonical digest of body',
        field: 'planSha',
      });
    }

    // 5. Repo / issue / spec digest must agree with spec.
    if (plan.repo !== spec.repo || plan.issueNumber !== spec.issueNumber) {
      findings.push({
        level: 'error',
        code: 'spec_mismatch',
        message: 'plan repo/issueNumber does not match spec',
        field: 'repo',
      });
    }

    // 6. Risk floor must appear on the plan — for every protected path
    //    the deterministic classifier flagged, every task must either
    //    forbid it OR explicitly allow it AND the task must be tagged
    //    at a model tier the severity demands.
    if (this.options.enforceForbiddenProtectedPaths ?? true) {
      const requiredTier = minModelTierForSeverity(deterministicRisk.severity);
      for (const match of deterministicRisk.matches) {
        for (const t of plan.tasks) {
          const explicitlyAllows = t.allowedPaths.some((p) => p.includes(match.pattern));
          if (explicitlyAllows) {
            // Model tier must meet the floor.
            if (severityRank(deterministicRisk.severity) > 0) {
              if (modelTierRank(t.modelTier) < modelTierRank(requiredTier)) {
                findings.push({
                  level: 'error',
                  code: 'insufficient_model_tier',
                  message: `task ${t.id} touches ${match.pattern} (${match.bucket}) but modelTier ${t.modelTier} < required ${requiredTier}`,
                  field: 'tasks.modelTier',
                });
              }
            }
          } else {
            // Path not explicitly allowed → must be forbidden.
            const forbidsIt = t.forbiddenPaths.some((p) => p.includes(match.pattern));
            if (!forbidsIt) {
              findings.push({
                level: 'error',
                code: 'missing_forbidden_path',
                message: `task ${t.id} must forbid ${match.pattern} (${match.bucket}) because it does not allow-list it`,
                field: 'tasks.forbiddenPaths',
              });
            }
          }
        }
      }
    }

    return findings;
  }
}

function findsCycle(tasks: readonly ImplementationTask[]): boolean {
  const adj = new Map<string, readonly string[]>();
  for (const t of tasks) adj.set(t.id, t.dependsOn);
  const color = new Map<string, 'white' | 'gray' | 'black'>(tasks.map((t) => [t.id, 'white']));
  const visit = (id: string, stack: string[]): boolean => {
    const c = color.get(id);
    if (c === 'gray') return true;
    if (c === 'black') return false;
    color.set(id, 'gray');
    const deps = adj.get(id) ?? [];
    for (const d of deps) {
      if (visit(d, [...stack, id])) return true;
    }
    color.set(id, 'black');
    return false;
  };
  for (const t of tasks) {
    if (visit(t.id, [])) return true;
  }
  return false;
}

const MODEL_TIER_RANK: Record<ModelTier, number> = {
  low: 0,
  standard: 1,
  high: 2,
  frontier: 3,
};

export function modelTierRank(t: ModelTier): number {
  return MODEL_TIER_RANK[t];
}

/**
 * Minimum model tier required for a given deterministic severity.
 *   - low:      low
 *   - medium:   standard
 *   - high:     high
 *   - critical: frontier
 */
export function minModelTierForSeverity(s: PathMatch['severity']): ModelTier {
  switch (s) {
    case 'low':
      return 'low';
    case 'medium':
      return 'standard';
    case 'high':
      return 'high';
    case 'critical':
      return 'frontier';
  }
}

/**
 * Plan prompt template — trusted. The orchestrator interpolates the
 * RequirementSpec (TRUSTED — cgao generated it) into the system region
 * of the prompt and the issue body only inside the untrusted envelope.
 *
 * Note: the spec itself is cgao-authoritative. The issue body is still
 * untrusted, so the template carries the envelope.
 */
export const PLAN_PROMPT_TEMPLATE = `You are cgao, a planning agent.

Your task: produce an ImplementationPlan for the issue below, given the RequirementSpec.

# Output schema (JSON)
{
  "planId": "plan-0001",
  "tasks": [
    {
      "id": "t1",
      "satisfies": ["ac-1"],
      "description": "...",
      "allowedPaths": ["src/foo.ts"],
      "forbiddenPaths": ["src/auth/"],
      "dependsOn": [],
      "agent": "implementer",
      "modelTier": "standard"
    }
  ]
}

# Rules
- EVERY acceptance_criterion id (ac-1, ac-2, ...) MUST appear in at
  least one task's "satisfies" list.
- Each task must declare:
    * allowedPaths  — paths it MAY read/write (closed universe)
    * forbiddenPaths — paths it must NOT touch (enforced by FS sandbox)
    * dependsOn      — task ids that must finish first
    * agent          — explorer|implementer|tester|reviewer|committer
    * modelTier      — low|standard|high|frontier
- A path that appears in the deterministic risk classifier's matches
  MUST appear in forbiddenPaths UNLESS the task is explicitly scoped to
  touch it (in which case modelTier must meet the severity floor).
- You CANNOT lower the risk floor. cgao re-runs the classifier and
  rejects plans that under-state it.
- You CANNOT approve or merge anything.

# RequirementSpec (TRUSTED — cgao-authored)
{{requirementSpecJson}}

<<<UNTRUSTED_CONTENT BEGIN>>>
ISSUE_TITLE: {{title}}
ISSUE_BODY:
{{body}}
<<<UNTRUSTED_CONTENT END>>>

Return JSON only.`;

export function renderPlanPrompt(args: {
  requirementSpecJson: string;
  title: string;
  body: string;
}): string {
  return PLAN_PROMPT_TEMPLATE.replace('{{requirementSpecJson}}', args.requirementSpecJson)
    .replace('{{title}}', args.title)
    .replace('{{body}}', args.body);
}
