/**
 * Status comment manager — T-M3-002, spec §14.2.
 *
 * cgao maintains ONE "active" status comment per issue. The comment is
 * generated by the orchestrator and contains an authenticated marker
 * (HMAC of repo+issue+run+authorLogin using the CGAO_CONTROL_TOKEN).
 *
 * On every internal status change, cgao edits the SAME comment rather
 * than posting a new one. This keeps the audit surface small and lets
 * humans rely on "the first cgao comment" being the source of truth.
 *
 * Contracts (spec §14.2):
 *
 *   - At most one active status comment per run per issue.
 *   - The comment author MUST be the cgao GitHub App bot. Comments
 *     with a forged marker that aren't authored by the bot are
 *     ignored when updating.
 *   - Forged markers (constructed without the secret) are detected
 *     by HMAC verification — they cannot cause a status mutation.
 *
 * This module is pure: it generates the comment body + marker and
 * owns the StatusCommentRepository interface. The actual GitHub API
 * calls live in adapters.
 */

import { createHmac, randomUUID, timingSafeEqual } from 'node:crypto';
import type { IssueStatus } from './triage.js';

export interface StatusCommentRecord {
  /** GitHub comment id. */
  commentId: number;
  /** The repo full name, e.g. 'cgao/test'. */
  repo: string;
  /** Issue number. */
  issueNumber: number;
  /** The run id this comment belongs to. */
  runId: string;
  /** The marker string the comment was tagged with. */
  marker: string;
  /** Author login of the comment (must match cgao bot login). */
  authorLogin: string;
  /** ISO-8601 created_at timestamp. */
  createdAt: string;
  /** ISO-8601 updated_at timestamp. */
  updatedAt: string;
  /** Status the comment currently shows. */
  status: IssueStatus;
}

export interface StatusCommentRepository {
  /** Find the active cgao status comment for the issue (or null). */
  findActive(args: {
    repo: string;
    issueNumber: number;
    cgaoBotLogin: string;
  }): Promise<StatusCommentRecord | null>;
  /** Create a new comment, returning the record. */
  create(args: {
    repo: string;
    issueNumber: number;
    body: string;
    marker: string;
    runId: string;
    cgaoBotLogin: string;
    now: Date;
    status: IssueStatus;
  }): Promise<StatusCommentRecord>;
  /** Edit the body of an existing comment. */
  update(args: {
    commentId: number;
    body: string;
    marker: string;
    now: Date;
    status: IssueStatus;
  }): Promise<StatusCommentRecord>;
}

export interface StatusCommentConfig {
  cgaoBotLogin: string;
  /** HMAC secret — the CGAO_CONTROL_TOKEN. */
  markerSecret: string;
}

export const STATUS_COMMENT_MARKER_BEGIN = '<!-- cgao:status-comment-marker';
export const STATUS_COMMENT_MARKER_END = '-->';

/**
 * Generate the marker HMAC. The HMAC input is:
 *   `${repo}\n${issueNumber}\n${runId}\n${authorLogin}\n${status}\n${nonce}`
 *
 * The nonce is included so that two updates for the same run/status
 * don't produce identical markers — that allows the orchestrator to
 * distinguish stale-but-valid markers from fresh ones.
 */
export function generateStatusMarker(args: {
  secret: string;
  repo: string;
  issueNumber: number;
  runId: string;
  authorLogin: string;
  status: IssueStatus;
  nonce?: string;
}): string {
  const nonce = args.nonce ?? randomUUID();
  const data = [
    args.repo,
    String(args.issueNumber),
    args.runId,
    args.authorLogin,
    args.status,
    nonce,
  ].join('\n');
  const mac = createHmac('sha256', args.secret).update(data).digest('hex');
  // Marker carries enough metadata for the bot to find+verify on edit.
  return `${STATUS_COMMENT_MARKER_BEGIN} run=${args.runId} status=${args.status} nonce=${nonce} mac=${mac} ${STATUS_COMMENT_MARKER_END}`;
}

export interface ParsedMarker {
  runId: string;
  status: IssueStatus;
  nonce: string;
  mac: string;
}

/**
 * Parse the marker from a comment body. Returns null if no marker is
 * found or its structure is malformed — callers MUST treat null as
 * "comment is not an authenticated cgao status comment".
 */
export function parseStatusMarker(body: string): ParsedMarker | null {
  const m = body.match(
    /<!--\s*cgao:status-comment-marker\s+run=([^\s]+)\s+status=([^\s]+)\s+nonce=([^\s]+)\s+mac=([0-9a-f]+)\s*-->/u,
  );
  if (!m) return null;
  const [, runId, status, nonce, mac] = m;
  if (!runId || !status || !nonce || !mac) return null;
  return { runId, status: status as IssueStatus, nonce, mac };
}

/**
 * Verify a parsed marker against the secret. Constant-time on the MAC.
 */
export function verifyStatusMarker(args: {
  secret: string;
  repo: string;
  issueNumber: number;
  parsed: ParsedMarker;
  authorLogin: string;
}): boolean {
  const data = [
    args.repo,
    String(args.issueNumber),
    args.parsed.runId,
    args.authorLogin,
    args.parsed.status,
    args.parsed.nonce,
  ].join('\n');
  const expected = createHmac('sha256', args.secret).update(data).digest('hex');
  return constantTimeHexEqual(expected, args.parsed.mac);
}

/**
 * Render the markdown body cgao posts as the status comment.
 *
 *   ## cgao status
 *   <status line>
 *
 *   <details><summary>cgao metadata</summary>
 *   ...
 *   </details>
 *   <!-- marker -->
 */
export function renderStatusCommentBody(args: {
  status: IssueStatus;
  category?: string;
  missingFields?: readonly string[];
  marker: string;
  note?: string;
}): string {
  const lines: string[] = ['## cgao status', ''];
  lines.push(`**Status:** \`${args.status}\``);
  if (args.category) lines.push(`**Kind:** \`${args.category}\``);
  if (args.missingFields && args.missingFields.length > 0) {
    lines.push(`**Needs:** ${args.missingFields.map((f) => `\`${f}\``).join(', ')}`);
  }
  if (args.note) {
    lines.push('');
    lines.push(args.note);
  }
  lines.push('');
  lines.push(args.marker);
  return lines.join('\n');
}

export class StatusCommentService {
  constructor(
    private readonly repo: StatusCommentRepository,
    private readonly config: StatusCommentConfig,
  ) {}

  /**
   * Update or create the active status comment for an issue. If an
   * existing comment authored by the cgao bot has a valid marker, we
   * edit it. If the existing comment has NO marker or a forged marker,
   * we create a new one (the old one is treated as user content).
   *
   * Returns the persisted record.
   */
  async upsert(args: {
    repo: string;
    issueNumber: number;
    runId: string;
    status: IssueStatus;
    category?: string;
    missingFields?: readonly string[];
    note?: string;
    now?: Date;
  }): Promise<StatusCommentRecord> {
    const now = args.now ?? new Date();
    const existing = await this.repo.findActive({
      repo: args.repo,
      issueNumber: args.issueNumber,
      cgaoBotLogin: this.config.cgaoBotLogin,
    });

    if (
      existing &&
      existing.authorLogin === this.config.cgaoBotLogin &&
      existing.repo === args.repo
    ) {
      // Existing comment is by the cgao bot — re-mint a marker for
      // this update and edit the body.
      const marker = generateStatusMarker({
        secret: this.config.markerSecret,
        repo: args.repo,
        issueNumber: args.issueNumber,
        runId: args.runId,
        authorLogin: this.config.cgaoBotLogin,
        status: args.status,
      });
      const body = renderStatusCommentBody({
        status: args.status,
        category: args.category,
        missingFields: args.missingFields,
        note: args.note,
        marker,
      });
      return this.repo.update({
        commentId: existing.commentId,
        body,
        marker,
        now,
        status: args.status,
      });
    }

    // No existing bot-authored comment — create one.
    const marker = generateStatusMarker({
      secret: this.config.markerSecret,
      repo: args.repo,
      issueNumber: args.issueNumber,
      runId: args.runId,
      authorLogin: this.config.cgaoBotLogin,
      status: args.status,
    });
    const body = renderStatusCommentBody({
      status: args.status,
      category: args.category,
      missingFields: args.missingFields,
      note: args.note,
      marker,
    });
    return this.repo.create({
      repo: args.repo,
      issueNumber: args.issueNumber,
      body,
      marker,
      runId: args.runId,
      cgaoBotLogin: this.config.cgaoBotLogin,
      now,
      status: args.status,
    });
  }

  /**
   * Verify whether an incoming comment body is an authenticated cgao
   * status comment for the given repo+issue. Returns true only when
   * the marker parses cleanly AND the HMAC matches.
   *
   * Humans cannot forge this without the CGAO_CONTROL_TOKEN.
   */
  isAuthenticated(args: { body: string; repo: string; issueNumber: number }): boolean {
    const parsed = parseStatusMarker(args.body);
    if (!parsed) return false;
    return verifyStatusMarker({
      secret: this.config.markerSecret,
      repo: args.repo,
      issueNumber: args.issueNumber,
      parsed,
      authorLogin: this.config.cgaoBotLogin,
    });
  }
}

/**
 * In-memory repository for unit tests.
 */
export class InMemoryStatusCommentRepository implements StatusCommentRepository {
  private readonly rows = new Map<number, StatusCommentRecord>();
  private nextId = 1;

  async findActive(args: {
    repo: string;
    issueNumber: number;
    cgaoBotLogin: string;
  }): Promise<StatusCommentRecord | null> {
    for (const row of this.rows.values()) {
      if (
        row.repo === args.repo &&
        row.issueNumber === args.issueNumber &&
        row.authorLogin === args.cgaoBotLogin
      ) {
        return row;
      }
    }
    return null;
  }

  async create(args: {
    repo: string;
    issueNumber: number;
    body: string;
    marker: string;
    runId: string;
    cgaoBotLogin: string;
    now: Date;
    status: IssueStatus;
  }): Promise<StatusCommentRecord> {
    const id = this.nextId++;
    const record: StatusCommentRecord = {
      commentId: id,
      repo: args.repo,
      issueNumber: args.issueNumber,
      runId: args.runId,
      marker: args.marker,
      authorLogin: args.cgaoBotLogin,
      createdAt: args.now.toISOString(),
      updatedAt: args.now.toISOString(),
      status: args.status,
    };
    this.rows.set(id, record);
    return record;
  }

  async update(args: {
    commentId: number;
    body: string;
    marker: string;
    now: Date;
    status: IssueStatus;
  }): Promise<StatusCommentRecord> {
    const existing = this.rows.get(args.commentId);
    if (!existing) throw new Error(`status comment ${args.commentId} not found`);
    const updated: StatusCommentRecord = {
      ...existing,
      marker: args.marker,
      updatedAt: args.now.toISOString(),
      status: args.status,
    };
    this.rows.set(args.commentId, updated);
    return updated;
  }

  /** Test helper: inject a row that simulates a forged-marker comment. */
  injectForged(args: {
    repo: string;
    issueNumber: number;
    authorLogin: string;
    body: string;
  }): StatusCommentRecord {
    const id = this.nextId++;
    const now = new Date().toISOString();
    const record: StatusCommentRecord = {
      commentId: id,
      repo: args.repo,
      issueNumber: args.issueNumber,
      runId: 'forged',
      marker: '<!-- forged -->',
      authorLogin: args.authorLogin,
      createdAt: now,
      updatedAt: now,
      status: 'new',
    };
    this.rows.set(id, record);
    return record;
  }
}

function constantTimeHexEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  const ab = Buffer.from(a, 'hex');
  const bb = Buffer.from(b, 'hex');
  if (ab.length !== bb.length) return false;
  return timingSafeEqual(ab, bb);
}
